apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hasher-netpol
spec:
  podSelector:
    matchLabels:
      name: hasher-rc
  ingress:
    - 
      from:
        - 
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: gca-dockercoins-2
          podSelector:
            matchLabels:
              name: worker-rc
        - 
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: gca-phpinfo
          podSelector:
            matchLabels:
              name: worker-rc
      ports:
        - 
          protocol: TCP
          port: 8080
